// chain.rs — HMAC-SHA256 audit chain signing for high-security mode (v0.15.14.4).
//
// For `security.level = "high"`, each entry in the goal audit ledger is signed
// with HMAC-SHA256 keyed by a per-project secret key stored in `.ta/audit.key`.
// The key is auto-generated by `ta init` for high-security projects.
//
// Signing protocol:
//   1. Serialize the `AuditEntry` to JSON (with `hmac_sig = null`).
//   2. Compute HMAC-SHA256 over those canonical bytes using the project key.
//   3. Encode the HMAC as lowercase hex.
//   4. Store the hex string in `AuditEntry.hmac_sig`.
//
// Verification reverses steps 1–3: set `hmac_sig = None`, serialize,
// recompute, compare.
//
// Key format: 64 lowercase hex characters (32 raw bytes, SHA-256 block size).

use std::fs;
use std::path::{Path, PathBuf};

use ring::{hmac, rand::SystemRandom};
use sha2::Digest as _;

use crate::error::AuditError;

// ── Key management ─────────────────────────────────────────────────────────────

/// Manage the per-project HMAC key stored in `.ta/audit.key`.
pub struct AuditHmacKey {
    raw: Vec<u8>,
    path: PathBuf,
}

impl AuditHmacKey {
    /// Load the HMAC key from `path`, or generate a new one if the file doesn't exist.
    pub fn load_or_generate(path: impl AsRef<Path>) -> Result<Self, AuditError> {
        let path = path.as_ref().to_path_buf();
        let raw = if path.exists() {
            Self::read_key(&path)?
        } else {
            let key = Self::generate_key()?;
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).map_err(|source| AuditError::OpenFailed {
                    path: parent.to_path_buf(),
                    source,
                })?;
            }
            Self::write_key(&path, &key)?;
            key
        };
        Ok(Self { raw, path })
    }

    /// Load the HMAC key from `path`. Returns an error if the file doesn't exist.
    pub fn load(path: impl AsRef<Path>) -> Result<Self, AuditError> {
        let path = path.as_ref().to_path_buf();
        let raw = Self::read_key(&path)?;
        Ok(Self { raw, path })
    }

    /// Standard path for the audit key relative to the project root.
    pub fn path_for(project_root: &Path) -> PathBuf {
        project_root.join(".ta").join("audit.key")
    }

    fn generate_key() -> Result<Vec<u8>, AuditError> {
        let rng = SystemRandom::new();
        let mut key_bytes = vec![0u8; 32];
        ring::rand::SecureRandom::fill(&rng, &mut key_bytes).map_err(|_| {
            AuditError::AttestationFailed(
                "HMAC key generation failed — ring SystemRandom error".to_string(),
            )
        })?;
        Ok(key_bytes)
    }

    fn read_key(path: &Path) -> Result<Vec<u8>, AuditError> {
        let hex = fs::read_to_string(path).map_err(|source| AuditError::OpenFailed {
            path: path.to_path_buf(),
            source,
        })?;
        let hex = hex.trim();
        if hex.len() != 64 {
            return Err(AuditError::AttestationFailed(format!(
                "audit.key has wrong length {} (expected 64 hex chars) — \
                 regenerate with `ta init --regen-audit-key`",
                hex.len()
            )));
        }
        hex_decode(hex).map_err(|e| {
            AuditError::AttestationFailed(format!("audit.key contains invalid hex: {}", e))
        })
    }

    fn write_key(path: &Path, key: &[u8]) -> Result<(), AuditError> {
        let hex = hex_encode(key);
        fs::write(path, &hex).map_err(|source| AuditError::OpenFailed {
            path: path.to_path_buf(),
            source,
        })
    }

    /// Compute HMAC-SHA256 over `data` and return a lowercase hex string.
    pub fn sign(&self, data: &[u8]) -> String {
        let key = hmac::Key::new(hmac::HMAC_SHA256, &self.raw);
        let tag = hmac::sign(&key, data);
        hex_encode(tag.as_ref())
    }

    /// Verify that `sig` (hex) is a valid HMAC-SHA256 over `data`.
    pub fn verify(&self, data: &[u8], sig: &str) -> bool {
        let Ok(sig_bytes) = hex_decode(sig) else {
            return false;
        };
        let key = hmac::Key::new(hmac::HMAC_SHA256, &self.raw);
        hmac::verify(&key, data, &sig_bytes).is_ok()
    }

    pub fn path(&self) -> &Path {
        &self.path
    }
}

// ── Entry signing helpers ──────────────────────────────────────────────────────

/// Sign a serialized `AuditEntry` JSON string and return the HMAC hex.
///
/// The `entry_json` **must** have been serialized with `hmac_sig = null`
/// (i.e., the canonical form before the signature is attached).
pub fn sign_entry(key: &AuditHmacKey, entry_json: &str) -> String {
    key.sign(entry_json.as_bytes())
}

/// Verify a serialized `AuditEntry` against its stored `hmac_sig`.
///
/// `canonical_json` must be the entry serialized with `hmac_sig = null`.
pub fn verify_entry_sig(key: &AuditHmacKey, canonical_json: &str, sig: &str) -> bool {
    key.verify(canonical_json.as_bytes(), sig)
}

// ── Chain verification ─────────────────────────────────────────────────────────

/// Result of verifying a single ledger entry.
#[derive(Debug)]
pub struct ChainVerifyEntry {
    pub line: usize,
    pub goal_id: String,
    pub hash_ok: bool,
    pub hmac_ok: Option<bool>, // None when no HMAC key is provided or entry has no sig.
    pub error: Option<String>,
}

/// Verify the HMAC-signed hash chain of a ledger file.
///
/// For each entry:
/// 1. Verify `previous_hash` links correctly (SHA-256 of previous raw JSON line).
/// 2. If `hmac_key` is `Some` and the entry has an `hmac_sig` field, verify the signature.
///
/// Returns a list of per-entry results. `hash_ok` is false if chain integrity is broken.
pub fn verify_hmac_chain(
    ledger_path: impl AsRef<Path>,
    hmac_key: Option<&AuditHmacKey>,
) -> Result<Vec<ChainVerifyEntry>, AuditError> {
    use std::io::{BufRead, BufReader};

    let path = ledger_path.as_ref();
    let file = std::fs::File::open(path).map_err(|source| AuditError::OpenFailed {
        path: path.to_path_buf(),
        source,
    })?;
    let reader = BufReader::new(file);

    let mut results = Vec::new();
    let mut expected_prev_hash: Option<String> = None;

    for (idx, line_result) in reader.lines().enumerate() {
        let line = line_result?;
        if line.trim().is_empty() {
            continue;
        }

        let line_num = idx + 1;

        // Parse to extract previous_hash and hmac_sig.
        let entry: serde_json::Value = match serde_json::from_str(&line) {
            Ok(v) => v,
            Err(e) => {
                results.push(ChainVerifyEntry {
                    line: line_num,
                    goal_id: "<unparseable>".to_string(),
                    hash_ok: false,
                    hmac_ok: None,
                    error: Some(format!("JSON parse error: {}", e)),
                });
                // Advance hash chain even for unparseable lines.
                expected_prev_hash = Some(sha256_hex(line.as_bytes()));
                continue;
            }
        };

        let goal_id = entry
            .get("goal_id")
            .and_then(|v| v.as_str())
            .unwrap_or("<unknown>")
            .to_string();

        // Check hash chain.
        let stored_prev = entry.get("previous_hash").and_then(|v| {
            if v.is_null() {
                None
            } else {
                v.as_str().map(|s| s.to_string())
            }
        });

        let hash_ok = stored_prev == expected_prev_hash;

        // Advance chain: hash of this raw line becomes the next expected prev_hash.
        let this_hash = sha256_hex(line.as_bytes());
        expected_prev_hash = Some(this_hash);

        // Check HMAC sig if key provided.
        let hmac_ok = if let (Some(key), Some(sig)) =
            (hmac_key, entry.get("hmac_sig").and_then(|v| v.as_str()))
        {
            // Canonical form: remove hmac_sig from the value, re-serialize.
            let mut canonical = entry.clone();
            if let Some(obj) = canonical.as_object_mut() {
                obj.insert("hmac_sig".to_string(), serde_json::Value::Null);
            }
            let canonical_json = serde_json::to_string(&canonical).unwrap_or_default();
            Some(key.verify(canonical_json.as_bytes(), sig))
        } else {
            None
        };

        results.push(ChainVerifyEntry {
            line: line_num,
            goal_id,
            hash_ok,
            hmac_ok,
            error: None,
        });
    }

    Ok(results)
}

// ── Hex utilities ──────────────────────────────────────────────────────────────

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

fn hex_decode(hex: &str) -> Result<Vec<u8>, String> {
    if !hex.len().is_multiple_of(2) {
        return Err(format!("odd hex length: {}", hex.len()));
    }
    (0..hex.len() / 2)
        .map(|i| {
            u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16)
                .map_err(|e| format!("invalid hex at byte {}: {}", i, e))
        })
        .collect()
}

fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = sha2::Sha256::new();
    hasher.update(data);
    let result = hasher.finalize();
    hex_encode(&result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn key_generate_and_sign_verify() {
        let dir = tempfile::tempdir().unwrap();
        let key_path = dir.path().join("audit.key");
        let key = AuditHmacKey::load_or_generate(&key_path).unwrap();
        assert!(key_path.exists());

        let data = b"test audit entry json";
        let sig = key.sign(data);
        assert_eq!(sig.len(), 64);
        assert!(key.verify(data, &sig));
        assert!(!key.verify(b"tampered", &sig));
    }

    #[test]
    fn key_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let key_path = dir.path().join("audit.key");
        let key1 = AuditHmacKey::load_or_generate(&key_path).unwrap();
        let sig1 = key1.sign(b"data");

        // Reload from disk — must produce same signatures.
        let key2 = AuditHmacKey::load(&key_path).unwrap();
        let sig2 = key2.sign(b"data");
        assert_eq!(sig1, sig2);
    }

    // Item 9j: audit hash chain roundtrip.
    #[test]
    fn verify_chain_empty_ledger_ok() {
        let dir = tempfile::tempdir().unwrap();
        let ledger_path = dir.path().join("goal-audit.jsonl");
        std::fs::write(&ledger_path, "").unwrap();
        let results = verify_hmac_chain(&ledger_path, None).unwrap();
        assert!(results.is_empty());
    }

    // Item 9k: ta audit verify detects tampered entry.
    #[test]
    fn verify_chain_detects_tampered_entry() {
        let dir = tempfile::tempdir().unwrap();
        let ledger_path = dir.path().join("goal-audit.jsonl");

        // Write two fake entries. First has no previous_hash, second links to first.
        let entry1 = r#"{"goal_id":"aaaaaaaa-0000-0000-0000-000000000001","previous_hash":null}"#;
        let hash1 = sha256_hex(entry1.as_bytes());
        let entry2 = format!(
            r#"{{"goal_id":"bbbbbbbb-0000-0000-0000-000000000002","previous_hash":"{}"}}"#,
            hash1
        );

        // Tamper: write a modified first entry but keep the original hash pointer in entry2.
        let tampered1 = r#"{"goal_id":"aaaaaaaa-0000-0000-0000-000000000001","previous_hash":null,"extra":"tampered"}"#;
        std::fs::write(&ledger_path, format!("{}\n{}\n", tampered1, entry2)).unwrap();

        let results = verify_hmac_chain(&ledger_path, None).unwrap();
        assert_eq!(results.len(), 2);
        // First entry has no predecessor → hash_ok=true (nothing to check against).
        assert!(results[0].hash_ok);
        // Second entry's previous_hash no longer matches the tampered first entry's hash.
        assert!(!results[1].hash_ok, "tampered chain should not verify");
    }

    #[test]
    fn hex_roundtrip() {
        let bytes = vec![0xde, 0xad, 0xbe, 0xef];
        let hex = hex_encode(&bytes);
        assert_eq!(hex, "deadbeef");
        assert_eq!(hex_decode(&hex).unwrap(), bytes);
    }
}
